# Generated by Django 3.2.6 on 2021-09-01 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_article_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_image',
        ),
    ]
